spring:
  config:
    import: file:./.env[.properties]
  profiles:
    include: secret
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: id, nickname, name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://concheese.net/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

springdoc:
  api-docs:
    path: "/api-docs/v1"
  swagger-ui:
    path: "/docs.html"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        context:
          annotation: TRACE
        web: DEBUG
        nodeValue: INFO

jwt:
  secret: ${JWT_SECRET}