spring:
  config:
    import: file:./.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

springdoc:
  api-docs:
    path: "/api-docs/v1"
  swagger-ui:
    path: "/docs.html"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        context:
          annotation: TRACE
        web: DEBUG
        nodeValue: INFO