name: Spring Boot & Gradle CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft

      - name: Make env.properties
        run: |
          # Create env.properties
          cd ./src/main/resources
          touch ./env.properties
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> ./env.properties
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./env.properties
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./env.properties

      - name: Make application-secret.yaml
        run: |
          cd ./src/main/resources
          touch ./application-secret.yaml
          echo "jwt:" >> ./application-secret.yaml
          echo "  secret: ${{ secrets.JWT_SECRET_KEY }}" >> ./application-secret.yaml
          echo "spring" >> ./application-secret.yaml
          echo "  security:" >> ./application-secret.yaml
          echo "    oauth2:" >> ./application-secret.yaml
          echo "      client:" >> ./application-secret.yaml
          echo "        registration:" >> ./application-secret.yaml
          echo "          naver:" >> ./application-secret.yaml
          echo "            client-id: ${{ secrets.NAVER_CLIENT_SECRET }}" >> ./application-secret.yaml
          echo "            client-secret: ${{ secrets.NAVER_CLIENT_SECRET }}" >> ./application-secret.yaml
          echo "            scope: id, nickname, name, email" >> ./application-secret.yaml
          echo "            client-name: Naver" >> ./application-secret.yaml
          echo "            authorization-grant-type: authorization_code" >> ./application-secret.yaml
          echo "            redirect-uri: http://localhost:8080/login/oauth2/code/naver" >> ./application-secret.yaml
          echo "        provider:" >> ./application-secret.yaml
          echo "          naver:" >> ./application-secret.yaml
          echo "            authorization-uri: https://nid.naver.com/oauth2.0/authorize" >> ./application-secret.yaml
          echo "            token-uri: https://nid.naver.com/oauth2.0/token" >> ./application-secret.yaml
          echo "            user-info-uri: https://openapi.naver.com/v1/nid/me" >> ./application-secret.yaml
          echo "            user-name-attribute: response" >> ./application-secret.yaml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
