name: Spring Boot & Gradle CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft

      - name: Make env.properties
        run: |
          # Create env.properties
          cd ./src/main/resources
          touch ./env.properties
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> ./env.properties
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./env.properties
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./env.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: access to firebase secrets
        run: |
            echo $FIREBASE_SECRET_KEY >> credentials.json | base64 --decode
        env:
            FIREBASE_SECRET_KEY: ${{secrets.CREDENTIALS}}
            
      - name: Build with Gradle
        run: ./gradlew clean build
